### ISSUE TITLE
Apply ImgProc to detected face?

### ISSUE THREAD

**Issue by Cortlandd** [Anton111111/CVPlayground#1]
Hello, I saw your repo and found you've made progress that I'm trying to get to. I've implemented the base mlkit contour detector. It draws to canvas, draws on contours, etc. Its at default. I want to apply ImgProc.cvtColor to the detected face inside the rectangle. But I'm not sure how to approach? Any tips?

**Comment by Anton111111** [comment]
Unfortunately, I postponed this task And I can not help; (

**Comment by Cortlandd** [comment]
I'm more curious on your implentation of what you currently have

**Comment by Anton111111** [comment]
The fact that now there is still not working. Do not waste time on this ...
